version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: kittygram_backend
    env_file: .env
    image: suhartsev/kittygram_backend
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    container_name: kittygram_frontend
    env_file: .env
    image: suhartsev/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    container_name: kittygram_gateway
    env_file: .env
    image: suhartsev/kittygram_gateway
    volumes:
      - static:/static
      - media:/app/media/
    ports:
      - 9000:80
    depends_on:
      - db
