version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: kittygram_db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: kittygram_backend
    image: suhartsev/kittygram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/

  frontend:
    container_name: kittygram_frontend
    image: suhartsev/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  gateway:
    container_name: kittygram_gateway
    image: suhartsev/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    ports:
      - 9000:80
